name: "SUPLA Virtual Device"
version: "3.3.0"
slug: "supla_virtual_device"
description: "SUPLA Virtual Device addon for Home Assistant"
url: "https://github.com/lukbek/supla-virtual-device"
startup: system
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
init: false
map:
  - "config:rw"
options:
  device_name: "SUPLA VIRTUAL DEVICE"
  server_host: "svrX.supla.org"
  protocol_version: 12
  email: ""
  mqtt_enabled: true
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: "user"
  mqtt_password: "password"
  mqtt_client_name: "supla-virtual-device"

schema:
  device_name: str
  server_host: str
  protocol_version: int(1,20)
  email: email
  mqtt_enabled: bool
  mqtt_host: str?
  mqtt_port: int(1,65535)?
  mqtt_username: str?
  mqtt_password: str?
  mqtt_client_name: str?
