name: "SUPLA Virtual Device"
version: "3.4.0"
slug: "supla_virtual_device"
description: "SUPLA Virtual Device addon with auto-restart and cloud watchdog"

startup: system
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
init: false
map:
  - "config:rw"
options:
  device_name: "SUPLA VIRTUAL DEVICE"
  server_host: "svrX.supla.org"
  protocol_version: 20
  email: ""
  mqtt_enabled: true
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: "user"
  mqtt_password: "password"
  mqtt_client_name: "supla-virtual-device"
  watchdog_enabled: false
  watchdog_code: ""
  watchdog_url: ""
  watchdog_interval: 60
schema:
  device_name: str
  server_host: str
  protocol_version: int(1,20)
  email: str
  mqtt_enabled: bool
  mqtt_host: str?
  mqtt_port: int(1,65535)?
  mqtt_username: str?
  mqtt_password: str?
  mqtt_client_name: str?
  watchdog_enabled: bool
  watchdog_code: str?
  watchdog_url: str?
  watchdog_interval: int(1,300)
