name: "SUPLA Virtual Device"
version: "4.2.0"
slug: "supla_virtual_device"
description: "SUPLA Virtual Device based on BBart19/virtual-supla with dedicated addon config file and MQTT watchdog"
url: "https://github.com/BBart19/hass-addons/tree/main/supla_virtual_device"
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
init: false
map:
  - type: addon_config
    read_only: false
  - type: homeassistant_config
    read_only: false
    path: /homeassistant
options:
  debug: false
schema:
  debug: bool
  config: "str?"
